"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { signIn, signOut, useSession } from "next-auth/react";

type Food = { id:number; name:string; category:string; location:string; quantity:string; expiry:string; icon:string; image?:string; status?:"Available"|"Opened"|"Eaten"|"Consumed"|"Donated"|"Spoiled"|"Discarded"; remaining?:number; opened?:string; price?:number; purchased?:string };
type Donation = { id:number; foodName:string; quantity:string; expiryDate:string; pickupArea:string; pickupDetails:string; donorName:string; contact:string; note:string; image?:string; claimed:boolean; createdAt:string };
type ShelfBins = "None"|"Left bin"|"Right bin"|"Left & right bins";
type Cabinet = { id:string; label:string; color:string; finish:string; shelfCount:number; shelfBins:ShelfBins[] };
type Refrigerator = { id:string; label:string; modelId:string };
type FridgePreset = { id:string; brand:string; model:string; name:string; type:"French door"|"Bottom freezer"|"Side-by-side"; capacity:string; colorName:string; color:string; zones:string[] };
type Panel = "capture"|"alerts"|"household"|"preferences"|"insights"|"ai"|null;

const seed: Food[] = [
  {id:1,name:"Fresh milk",category:"Dairy",location:"Refrigerator 1 · Right door",quantity:"1 liter",expiry:"2026-07-19",icon:"🥛"},
  {id:2,name:"Baby spinach",category:"Produce",location:"Refrigerator 1 · Big Fresh Zone",quantity:"1 bag",expiry:"2026-07-20",icon:"🥬"},
  {id:3,name:"Avocados",category:"Produce",location:"Countertop",quantity:"2 pieces",expiry:"2026-07-22",icon:"🥑"},
  {id:4,name:"Greek yogurt",category:"Dairy",location:"Refrigerator 1 · Top right shelf",quantity:"500 g",expiry:"2026-07-24",icon:"🥣"},
  {id:5,name:"Large eggs",category:"Dairy",location:"Refrigerator 1 · Top left shelf",quantity:"12 pieces",expiry:"2026-07-29",icon:"🥚"},
  {id:6,name:"Brown rice",category:"Grains",location:"Cabinet 1",quantity:"2 kg",expiry:"2027-02-14",icon:"🍚"},
  {id:7,name:"Canned tomatoes",category:"Canned",location:"Cabinet 2",quantity:"3 cans",expiry:"2027-08-15",icon:"🥫"},
];
const categories = ["Produce","Dairy","Grains","Canned","Frozen","Snacks","Other"];
const defaultShelfBins: ShelfBins[] = ["None","None","Left & right bins"];
const normalizeCabinet=(cabinet:Partial<Cabinet>,index:number):Cabinet=>({id:cabinet.id||`Cabinet ${index+1}`,label:cabinet.label||`Storage ${index+1}`,color:cabinet.color||"#8f694b",finish:cabinet.finish||"Matte",shelfCount:Math.min(8,Math.max(1,cabinet.shelfCount||3)),shelfBins:Array.from({length:Math.min(8,Math.max(1,cabinet.shelfCount||3))},(_,shelf)=>cabinet.shelfBins?.[shelf]||defaultShelfBins[shelf]||"None")});
const cabinetLocationsFor=(cabinet:Cabinet)=>Array.from({length:cabinet.shelfCount},(_,index)=>{const shelf=`${cabinet.id} · Shelf ${index+1}`;const bins=cabinet.shelfBins[index];return [shelf,...((bins==="Left bin"||bins==="Left & right bins")?[`${shelf} · Left bin`]:[]),...((bins==="Right bin"||bins==="Left & right bins")?[`${shelf} · Right bin`]:[])]}).flat();
const icons:Record<string,string>={Produce:"🥬",Dairy:"🥛",Grains:"🌾",Canned:"🥫",Frozen:"❄️",Snacks:"🍪",Other:"📦"};
const fridgePresets:FridgePreset[]=[
  {id:"lg-gr-b22ftqvb",brand:"LG",model:"GR-B22FTQVB",name:"LinearCooling French Door",type:"French door",capacity:"20.8 cu. ft.",colorName:"Western Black",color:"#242322",zones:["Top left shelf","Top right shelf","Big Fresh Zone","Left door","Right door","Bottom freezer"]},
  {id:"lg-rvf-x208mc",brand:"LG",model:"RVF-X208MC",name:"Smart Inverter French Door",type:"French door",capacity:"20.8 cu. ft.",colorName:"Matte Black",color:"#292b2b",zones:["Top left shelf","Top right shelf","Fresh drawer","Left door","Right door","Bottom freezer"]},
  {id:"lg-rvb-a127bm",brand:"LG",model:"RVB-A127BM",name:"Auto Ice Maker Bottom Freezer",type:"Bottom freezer",capacity:"12.7 cu. ft.",colorName:"Black Glass",color:"#181b1c",zones:["Top shelf","Middle shelf","Fresh Converter","Crisper drawer","Fridge door","Bottom freezer"]},
  {id:"lg-rvs-m245bm",brand:"LG",model:"RVS-M245BM",name:"Door-in-Door Side-by-Side",type:"Side-by-side",capacity:"24.5 cu. ft.",colorName:"Black Mirror",color:"#202528",zones:["Freezer upper","Freezer lower","Top fridge shelf","Middle fridge shelf","Bottom fridge shelf","Door-in-Door"]},
  {id:"samsung-rs90f65anftc",brand:"Samsung",model:"RS90F65ANFTC",name:"Bespoke AI Family Hub",type:"Side-by-side",capacity:"20.9 cu. ft.",colorName:"Black DOI",color:"#1f2022",zones:["Freezer upper","Freezer lower","Top fridge shelf","Middle fridge shelf","Bottom fridge shelf","Beverage door"]},
  {id:"samsung-rs57dg4000m9tc",brand:"Samsung",model:"RS57DG4000M9TC",name:"RS4000DC SpaceMax",type:"Side-by-side",capacity:"20.5 cu. ft.",colorName:"Refined Inox",color:"#aeb2b2",zones:["Freezer upper","Freezer lower","Top fridge shelf","Middle fridge shelf","Bottom fridge shelf","Fridge door"]},
  {id:"samsung-rs63r5591b4tc",brand:"Samsung",model:"RS63R5591B4/TC",name:"SpaceMax FlexZone",type:"Side-by-side",capacity:"24.3 cu. ft.",colorName:"Gentle Black Matt",color:"#303131",zones:["Freezer upper","Freezer lower","Top fridge shelf","FlexZone","Bottom fridge shelf","Fridge door"]},
];
const today = new Date(); today.setHours(0,0,0,0);
const daysLeft=(date:string)=>Math.ceil((new Date(date+"T00:00:00").getTime()-today.getTime())/86400000);
const fmt=(date:string)=>new Date(date+"T00:00:00").toLocaleDateString("en-PH",{month:"short",day:"numeric",year:"numeric"});
const readJson=async<T,>(response:Response)=>await response.json() as T;

export default function Home(){
  const {data:session,status:authStatus}=useSession();
  const firstName=session?.user?.name?.trim().split(/\s+/)[0]||"";
  const [foods,setFoods]=useState<Food[]>(seed); const [loaded,setLoaded]=useState(false);
  const [query,setQuery]=useState(""); const [filter,setFilter]=useState("All"); const [modal,setModal]=useState(false);
  const [editingFood,setEditingFood]=useState<Food|null>(null); const [entryImage,setEntryImage]=useState("");
  const [donateFood,setDonateFood]=useState<Food|null>(null); const [donations,setDonations]=useState<Donation[]>([]); const [donationsLoading,setDonationsLoading]=useState(true);
  const [toast,setToast]=useState(""); const [saved,setSaved]=useState(3);
  const [panel,setPanel]=useState<Panel>(null); const [barcode,setBarcode]=useState(""); const [scanResult,setScanResult]=useState("");
  const [aiQuestion,setAiQuestion]=useState(""); const [aiAnswer,setAiAnswer]=useState(""); const [aiImage,setAiImage]=useState(""); const [aiLoading,setAiLoading]=useState(false); const [recording,setRecording]=useState(false);
  const [members,setMembers]=useState(["You"]); const [newMember,setNewMember]=useState("");
  const [prefs,setPrefs]=useState({plantForward:true,quickMeals:true,familyFriendly:false,budgetFriendly:true,minutes:30,servings:3});
  const [alerts,setAlerts]=useState({browser:false,email:false,calendar:true,days:3,emailAddress:""});
  const [storageOpen,setStorageOpen]=useState(false);
  const [refrigerators,setRefrigerators]=useState<Refrigerator[]>([{id:"Refrigerator 1",label:"Main refrigerator",modelId:fridgePresets[0].id}]);
  const [cabinets,setCabinets]=useState<Cabinet[]>([{id:"Cabinet 1",label:"Grains & breakfast",color:"#a8784f",finish:"Wood",shelfCount:3,shelfBins:["None","None","Left & right bins"]},{id:"Cabinet 2",label:"Cans & cooking",color:"#637d68",finish:"Matte",shelfCount:3,shelfBins:["None","None","Left & right bins"]},{id:"Cabinet 3",label:"Snacks",color:"#d4a843",finish:"Painted",shelfCount:3,shelfBins:["None","None","Left & right bins"]}]);
  /* Local hydration is intentionally performed once after mount. */
  /* eslint-disable react-hooks/set-state-in-effect */
  useEffect(()=>{
    const setupRaw=localStorage.getItem("pantry-storage");let savedFridges:Refrigerator[]=[{id:"Refrigerator 1",label:"Main refrigerator",modelId:fridgePresets[0].id}];
    let savedCabinets:Cabinet[]=[{id:"Cabinet 1",label:"Grains & breakfast",color:"#a8784f",finish:"Wood",shelfCount:3,shelfBins:["None","None","Left & right bins"]},{id:"Cabinet 2",label:"Cans & cooking",color:"#637d68",finish:"Matte",shelfCount:3,shelfBins:["None","None","Left & right bins"]},{id:"Cabinet 3",label:"Snacks",color:"#d4a843",finish:"Painted",shelfCount:3,shelfBins:["None","None","Left & right bins"]}];
    if(setupRaw){const x=JSON.parse(setupRaw);const legacy:Record<string,string>={"French door":"lg-gr-b22ftqvb","Bottom freezer":"lg-rvb-a127bm","Side-by-side":"lg-rvs-m245bm","Top freezer":"samsung-rs57dg4000m9tc"};const legacyModel=fridgePresets.some(f=>f.id===x.fridgeModel)?x.fridgeModel:(legacy[x.fridgeModel]||fridgePresets[0].id);savedFridges=Array.isArray(x.refrigerators)?x.refrigerators.filter((r:Refrigerator)=>fridgePresets.some(f=>f.id===r.modelId)):(x.hasFridge===false?[]:[{id:"Refrigerator 1",label:"Main refrigerator",modelId:legacyModel}]);savedCabinets=Array.isArray(x.cabinets)?x.cabinets.map((cabinet:Partial<Cabinet>,index:number)=>normalizeCabinet(cabinet,index)):savedCabinets;setRefrigerators(savedFridges);setCabinets(savedCabinets)}
    const raw=localStorage.getItem("pantry-foods");if(raw){const legacyZones=new Set(fridgePresets.flatMap(f=>f.zones));const first=savedFridges[0];const model=fridgePresets.find(f=>f.id===first?.modelId);setFoods((JSON.parse(raw) as Food[]).map(food=>{if(first&&legacyZones.has(food.location)){const direct=model?.zones.find(zone=>zone===food.location);const hint=food.location.toLowerCase();const matched=direct||model?.zones.find(zone=>hint.includes("door")&&zone.toLowerCase().includes("door"))||model?.zones.find(zone=>(hint.includes("crisper")||hint.includes("fresh"))&&(zone.toLowerCase().includes("fresh")||zone.toLowerCase().includes("crisper")))||model?.zones.find(zone=>hint.includes("middle")&&zone.toLowerCase().includes("middle"))||model?.zones.find(zone=>hint.includes("top")&&zone.toLowerCase().includes("top"))||model?.zones[0];return {...food,location:matched?`${first.id} · ${matched}`:"Unassigned"}}const cabinet=savedCabinets.find(item=>food.location===item.id||food.location.startsWith(`${item.id} · `));if(!cabinet||food.location===cabinet.id)return food;const legacySection=food.location.slice(cabinet.id.length+3);const shelf=legacySection==="Upper shelf"?1:legacySection==="Middle shelf"?2:legacySection==="Lower shelf"?3:1;const bin=legacySection==="Left bin"?" · Left bin":legacySection==="Right bin"?" · Right bin":"";return {...food,location:`${cabinet.id} · Shelf ${Math.min(shelf,cabinet.shelfCount)}${bin}`}}))}
    const s=localStorage.getItem("pantry-saved");if(s)setSaved(+s);const smart=localStorage.getItem("pantry-smart");if(smart){const x=JSON.parse(smart);if(x.members)setMembers(x.members);if(x.prefs)setPrefs(x.prefs);if(x.alerts)setAlerts(x.alerts)}setLoaded(true)
  },[]);
  /* eslint-enable react-hooks/set-state-in-effect */
  useEffect(()=>{if(loaded)localStorage.setItem("pantry-foods",JSON.stringify(foods))},[foods,loaded]);
  useEffect(()=>{if(loaded)localStorage.setItem("pantry-storage",JSON.stringify({refrigerators,cabinets}))},[refrigerators,cabinets,loaded]);
  useEffect(()=>{if(loaded)localStorage.setItem("pantry-smart",JSON.stringify({members,prefs,alerts}))},[members,prefs,alerts,loaded]);
  useEffect(()=>{fetch("/api/donations").then(async response=>{const data=await readJson<{error?:string;donations?:Donation[]}>(response);if(!response.ok)throw new Error(data.error||"Unable to open Public Pantry");setDonations(data.donations||[])}).catch(()=>setDonations([])).finally(()=>setDonationsLoading(false))},[]);
  const refrigeratorLocations=refrigerators.flatMap(refrigerator=>{const model=fridgePresets.find(f=>f.id===refrigerator.modelId);return (model?.zones||[]).map(zone=>`${refrigerator.id} · ${zone}`)});
  const cabinetLocations=cabinets.flatMap(c=>[c.id,...cabinetLocationsFor(c)]);
  const allLocations=[...refrigeratorLocations,"Unassigned","Countertop",...cabinetLocations];
  const isActive=(f:Food)=>!f.status||f.status==="Available"||f.status==="Opened";
  const canDonate=(f:Food)=>isActive(f)&&daysLeft(f.expiry)>=0&&daysLeft(f.expiry)<=3;
  const eligibleDonations=foods.filter(canDonate).sort((a,b)=>a.expiry.localeCompare(b.expiry));
  const sorted=useMemo(()=>foods.filter(f=>(filter==="All"||f.category===filter)&&f.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.expiry.localeCompare(b.expiry)),[foods,filter,query]);
  const soon=foods.filter(f=>isActive(f)&&daysLeft(f.expiry)<=7).sort((a,b)=>a.expiry.localeCompare(b.expiry));
  const recipeBank=[
    {title:"Creamy spinach & avocado eggs",emoji:"🍳",time:"12 min",meal:"Breakfast",uses:["spinach","avocado","egg"],steps:"Wilt the spinach, fold into soft eggs, then top with sliced avocado."},
    {title:"Berry yogurt rescue smoothie",emoji:"🥤",time:"5 min",meal:"Snack",uses:["yogurt","milk","berry"],steps:"Blend yogurt and milk with any fruit, ice, and a pinch of cinnamon."},
    {title:"Golden pantry rice bowl",emoji:"🥗",time:"20 min",meal:"Lunch",uses:["rice","spinach","egg","avocado"],steps:"Layer warm rice, sautéed greens, egg, and avocado with a light soy dressing."},
    {title:"Quick tomato shakshuka",emoji:"🍅",time:"18 min",meal:"Dinner",uses:["tomato","egg","spinach"],steps:"Simmer tomatoes with spices, add spinach, crack in eggs, and cover until set."},
    {title:"Overnight yogurt oats",emoji:"🥣",time:"5 min prep",meal:"Tomorrow",uses:["yogurt","milk","oat"],steps:"Mix oats, yogurt, and milk tonight; chill and top with fruit tomorrow."},
  ];
  const recipes=recipeBank.map(r=>({...r,matches:foods.filter(f=>isActive(f)&&r.uses.some(u=>f.name.toLowerCase().includes(u))&&daysLeft(f.expiry)<=7)})).filter(r=>r.matches.length).sort((a,b)=>b.matches.length-a.matches.length).slice(0,3);
  const showToast=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2600)};
  const openAddFood=()=>{setEditingFood(null);setEntryImage("");setModal(true)};
  const openEditFood=(food:Food)=>{setEditingFood(food);setEntryImage(food.image||"");setModal(true)};
  const closeFoodForm=()=>{setModal(false);setEditingFood(null);setEntryImage("")};
  const chooseFoodImage=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const max=900;const scale=Math.min(1,max/Math.max(image.width,image.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext("2d")?.drawImage(image,0,0,canvas.width,canvas.height);setEntryImage(canvas.toDataURL("image/jpeg",.78));showToast("Food photo ready")};image.src=String(reader.result)};reader.readAsDataURL(file)};
  const openPublicPantry=()=>document.getElementById("public-pantry")?.scrollIntoView({behavior:"smooth",block:"start"});
  const offerDonation=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!donateFood||!canDonate(donateFood)){setDonateFood(null);showToast("This food is no longer eligible to donate");return}const fd=new FormData(e.currentTarget);try{const response=await fetch("/api/donations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({foodName:donateFood.name,quantity:donateFood.quantity,expiryDate:donateFood.expiry,pickupArea:fd.get("pickupArea"),pickupDetails:fd.get("pickupDetails"),donorName:fd.get("donorName"),contact:fd.get("contact"),note:fd.get("note"),image:donateFood.image,status:donateFood.status||"Available",safeToShare:fd.get("safeToShare")==="on"})});const data=await readJson<{error?:string;donation:Donation}>(response);if(!response.ok)throw new Error(data.error);setDonations(v=>[data.donation,...v]);setDonateFood(null);showToast(`${donateFood.name} added to Public Pantry`)}catch(error){showToast(error instanceof Error?error.message:"Unable to post donation")}};
  const claimDonation=async(donation:Donation)=>{try{const response=await fetch("/api/donations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:donation.id})});if(!response.ok)throw new Error();setDonations(v=>v.filter(x=>x.id!==donation.id));setFoods(v=>v.map(f=>f.name===donation.foodName&&f.expiry===donation.expiryDate?{...f,status:"Donated"}:f));showToast(`${donation.foodName} marked as claimed`)}catch{showToast("Could not claim this donation. Please try again.")}};
  const setFoodStatus=(id:number,status:Food["status"])=>{const item=foods.find(f=>f.id===id);const wasActive=item?isActive(item):false;setFoods(v=>v.map(f=>f.id===id?{...f,status}:f));if(wasActive&&(status==="Eaten"||status==="Consumed")){setSaved(v=>{localStorage.setItem("pantry-saved",String(v+1));return v+1})}showToast(`${item?.name} marked as ${status?.toLowerCase()}`)};
  const consumeItem=(id:number)=>setFoodStatus(id,"Consumed");
  const moveFood=(id:number,location:string)=>{setFoods(v=>v.map(f=>f.id===id?{...f,location}:f));showToast(`Storage location updated`)};
  const addRefrigerator=()=>{
    if(refrigerators.length>=6){showToast("You can add up to 6 refrigerators");return}
    const used=new Set(refrigerators.map(r=>r.id));let number=1;while(used.has(`Refrigerator ${number}`))number+=1;
    setRefrigerators(v=>[...v,{id:`Refrigerator ${number}`,label:`Refrigerator ${number}`,modelId:fridgePresets[(number-1)%fridgePresets.length].id}]);showToast(`Refrigerator ${number} added`)
  };
  const updateRefrigeratorModel=(id:string,modelId:string)=>{const model=fridgePresets.find(f=>f.id===modelId);if(!model)return;setFoods(v=>v.map(food=>{if(!food.location.startsWith(`${id} · `))return food;const zone=food.location.slice(id.length+3);return model.zones.includes(zone)?food:{...food,location:"Unassigned"}}));setRefrigerators(v=>v.map(refrigerator=>refrigerator.id===id?{...refrigerator,modelId}:refrigerator));showToast("Refrigerator model updated")};
  const deleteRefrigerator=(refrigerator:Refrigerator)=>{if(!window.confirm(`Delete ${refrigerator.label || refrigerator.id}? Food stored there will be moved to Unassigned.`))return;setFoods(v=>v.map(food=>food.location.startsWith(`${refrigerator.id} · `)?{...food,location:"Unassigned"}:food));setRefrigerators(v=>v.filter(item=>item.id!==refrigerator.id));showToast(`${refrigerator.label || refrigerator.id} deleted`)};
  const addCabinet=()=>{
    if(cabinets.length>=12){showToast("You can add up to 12 cabinets");return}
    const used=new Set(cabinets.map(c=>c.id));let number=1;while(used.has(`Cabinet ${number}`))number+=1;
    const colors=["#8f694b","#547166","#c18a3f","#7b627f","#567286","#9a5c52"];
    const finishes=["Wood","Matte","Painted","Gloss"];
    setCabinets(v=>[...v,{id:`Cabinet ${number}`,label:`Storage ${number}`,color:colors[(number-1)%colors.length],finish:finishes[(number-1)%finishes.length],shelfCount:3,shelfBins:["None","None","Left & right bins"]}]);
    showToast(`Cabinet ${number} added`);
  };
  const deleteCabinet=(cabinet:Cabinet)=>{if(!window.confirm(`Delete ${cabinet.label || cabinet.id}? Food stored there will be moved to Unassigned.`))return;setFoods(v=>v.map(food=>food.location===cabinet.id||food.location.startsWith(`${cabinet.id} · `)?{...food,location:"Unassigned"}:food));setCabinets(v=>v.filter(item=>item.id!==cabinet.id));showToast(`${cabinet.label || cabinet.id} deleted`)};
  const updateShelfCount=(cabinet:Cabinet,shelfCount:number)=>{const affected=foods.filter(food=>food.location.startsWith(`${cabinet.id} · Shelf `)&&Number(food.location.match(/Shelf (\d+)/)?.[1]||0)>shelfCount);if(affected.length&& !window.confirm(`Remove ${cabinet.shelfCount-shelfCount} shelf${cabinet.shelfCount-shelfCount===1?"":"s"}? ${affected.length} affected food item${affected.length===1?"":"s"} will move to Unassigned.`))return;setFoods(v=>v.map(food=>affected.some(item=>item.id===food.id)?{...food,location:"Unassigned"}:food));setCabinets(v=>v.map(item=>item.id===cabinet.id?{...item,shelfCount,shelfBins:Array.from({length:shelfCount},(_,index)=>item.shelfBins[index]||"None")}:item));showToast(`${cabinet.id} now has ${shelfCount} shelves`)};
  const updateShelfBins=(cabinet:Cabinet,shelfIndex:number,bins:ShelfBins)=>{const shelf=`${cabinet.id} · Shelf ${shelfIndex+1}`;const keepLeft=bins==="Left bin"||bins==="Left & right bins";const keepRight=bins==="Right bin"||bins==="Left & right bins";setFoods(v=>v.map(food=>food.location===`${shelf} · Left bin`&&!keepLeft?{...food,location:shelf}:food.location===`${shelf} · Right bin`&&!keepRight?{...food,location:shelf}:food));setCabinets(v=>v.map(item=>item.id===cabinet.id?{...item,shelfBins:item.shelfBins.map((value,index)=>index===shelfIndex?bins:value)}:item));showToast(`${cabinet.id} shelf ${shelfIndex+1} bins updated`)};
  const setRemaining=(id:number,remaining:number)=>setFoods(v=>v.map(f=>f.id===id?{...f,remaining}:f));
  const scanBarcode=()=>{const products:Record<string,{name:string;category:string;icon:string}>={"4800016641016":{name:"Fresh milk",category:"Dairy",icon:"🥛"},"4800361418219":{name:"Whole wheat bread",category:"Grains",icon:"🍞"},"4804888589012":{name:"Greek yogurt",category:"Dairy",icon:"🥣"}};const p=products[barcode]||{name:"Recognized grocery item",category:"Other",icon:"📦"};setScanResult(`${p.icon} ${p.name} identified`);showToast("Barcode recognized — add expiry and storage next")};
  const askAi=async(mode:"chat"|"recipes"|"vision"="chat",question=aiQuestion,image=aiImage)=>{setAiLoading(true);setAiAnswer("");try{const response=await fetch("/api/ai/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,prompt:question,image,inventory:foods.filter(isActive),preferences:prefs})});const data=await readJson<{error?:string;answer?:string}>(response);if(!response.ok)throw new Error(data.error);setAiAnswer(data.answer||"No suggestion was returned.")}catch(error){setAiAnswer(error instanceof Error?error.message:"The AI assistant is unavailable.")}finally{setAiLoading(false)}};
  const chooseAiImage=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const max=1000;const scale=Math.min(1,max/Math.max(image.width,image.height));const canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d")?.drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL("image/jpeg",.72);setAiImage(data);setPanel("ai");setAiQuestion("Identify the food, visible freshness clues, likely storage location, and any date visible in this image. Tell me what to verify manually.");void askAi("vision","Analyze this pantry or food photo.",data)};image.src=String(reader.result)};reader.readAsDataURL(file)};
  const recordVoice=async()=>{if(recording)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const recorder=new MediaRecorder(stream);const chunks:Blob[]=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=async()=>{stream.getTracks().forEach(track=>track.stop());setRecording(false);const form=new FormData();form.append("audio",new File(chunks,"pantry-voice.webm",{type:recorder.mimeType||"audio/webm"}));try{const response=await fetch("/api/ai/transcribe",{method:"POST",body:form});const data=await readJson<{error?:string;text:string}>(response);if(!response.ok)throw new Error(data.error);setAiQuestion(data.text);setPanel("ai");showToast("Voice entry transcribed")}catch(error){showToast(error instanceof Error?error.message:"Could not transcribe recording")}};recorder.start();setRecording(true);setTimeout(()=>recorder.state==="recording"&&recorder.stop(),8000)}catch{showToast("Microphone permission is required for voice entry")}};
  const listenToAnswer=async()=>{if(!aiAnswer)return;try{const response=await fetch("/api/ai/speech",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:aiAnswer})});if(!response.ok)throw new Error();const url=URL.createObjectURL(await response.blob());const audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);await audio.play()}catch{showToast("Audio could not be played")}};
  const requestAlerts=async()=>{if("Notification" in window){const result=await Notification.requestPermission();setAlerts(v=>({...v,browser:result==="granted"}));showToast(result==="granted"?"Browser alerts enabled":"Notification permission was not enabled")}};
  const downloadCalendar=()=>{const urgent=soon[0];const body=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:${urgent?.expiry.replaceAll("-","")||"20260719"}\nSUMMARY:Use ${urgent?.name||"expiring pantry food"}\nDESCRIPTION:Pantry Guardian expiry reminder\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([body],{type:"text/calendar"}));a.download="pantry-reminder.ics";a.click();showToast("Calendar reminder downloaded")};
  function saveFood(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const cat=String(fd.get("category"));const f:Food={...editingFood,id:editingFood?.id||Date.now(),name:String(fd.get("name")),quantity:String(fd.get("quantity")),category:cat,location:String(fd.get("location")),expiry:String(fd.get("expiry")),icon:icons[cat]||"📦",image:entryImage||undefined,remaining:Number(fd.get("remaining")||100),opened:String(fd.get("opened")||""),purchased:String(fd.get("purchased")||""),price:Number(fd.get("price")||0)};setFoods(v=>editingFood?v.map(x=>x.id===editingFood.id?f:x):[...v,f]);closeFoodForm();showToast(editingFood?`${f.name} updated`:`${f.name} added to your pantry`)}
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><img src="/pantry-guardian-logo-v3.png" alt="Pantry Guardian logo"/></div><div>Pantry<br/>Guardian</div></div>
      <nav><button className="active"><span>⌂</span>Today</button><button><span>▣</span>Pantry</button><button onClick={()=>setPanel("ai")}><span>✦</span>AI copilot</button><button onClick={()=>setPanel("capture")}><span>⌁</span>Smart capture</button><button onClick={()=>setStorageOpen(true)}><span>▦</span>Storage map</button><button><span>◷</span>Use soon <b>{soon.length}</b></button><button onClick={openPublicPantry}><span>♡</span>Public pantry <b>{donations.length}</b></button><button onClick={()=>setPanel("household")}><span>♙</span>Household</button><button onClick={()=>setPanel("insights")}><span>▥</span>Insights</button></nav>
      <div className="sidebar-account">{session?.user?<><i>{firstName.slice(0,1).toUpperCase()}</i><span><b>{session.user.name||"Pantry member"}</b><small>{session.user.email}</small></span><button onClick={()=>void signOut({callbackUrl:"/"})}>Sign out</button></>:<button className="google-login" disabled={authStatus==="loading"} onClick={()=>void signIn("google",{callbackUrl:"/"})}><i>G</i>{authStatus==="loading"?"Checking…":"Sign in with Google"}</button>}</div>
      <div className="impact"><span>🌿</span><strong>Waste less,<br/>save more.</strong><small>Every item used in time makes a difference.</small></div>
    </aside>
    <main>
      <header className="compact-hero"><div><div className="eyebrow">GOOD MORNING{firstName?`, ${firstName.toUpperCase()}`:""} <span>☀</span></div><h1>Save today’s food.<br/><em>Waste nothing.</em></h1><p>{soon.length?`${soon[0].name} needs attention first. You have ${soon.length} items to use this week.`:"Everything is on track—no urgent food today."}</p></div><div className="hero-actions"><button className="hero-account" onClick={()=>session?.user?void signOut({callbackUrl:"/"}):void signIn("google",{callbackUrl:"/"})}>{session?.user?<><i>{firstName.slice(0,1).toUpperCase()}</i>{firstName}</>:<><i>G</i> Google sign in</>}</button><button className="scan-main" onClick={()=>setPanel("capture")}>⌁ Smart capture</button><button className="add-main" onClick={openAddFood}><span>＋</span> Add food</button></div></header>
      <section className="today-plan"><div className="today-priority"><span>TODAY’S RESCUE PLAN</span><h2>{soon[0]?`Use ${soon[0].name} today`:"Your pantry is in great shape"}</h2><p>{soon[0]?`${soon[0].quantity} in ${soon[0].location} · ${soon[0].remaining??100}% remaining · ${daysLeft(soon[0].expiry)} day left`:"Check back tomorrow for your next action."}</p></div><div className="today-recipes">{recipes.slice(0,2).map(r=><button key={r.title} onClick={()=>showToast(`${r.title} added to today’s plan`)}><b>{r.emoji} {r.title}</b><small>{r.time} · uses {r.matches.length} urgent items</small></button>)}</div><div className="today-actions"><button onClick={()=>soon[0]&&consumeItem(soon[0].id)}>✓ Mark used</button><button onClick={()=>setPanel("alerts")}>◉ Remind me</button><button onClick={()=>soon[0]&&setRemaining(soon[0].id,Math.max(0,(soon[0].remaining??100)-25))}>−25% used</button></div></section>
      <section className="stats">
        <article><i className="mint">▣</i><div><small>Active items</small><strong>{foods.filter(isActive).length}</strong><span>{foods.filter(f=>!isActive(f)).length} in history</span></div></article>
        <article><i className="coral">◷</i><div><small>Use this week</small><strong>{soon.length}</strong><span>Needs your attention</span></div></article>
        <article><i className="lemon">♧</i><div><small>Food saved</small><strong>{saved}</strong><span>Great work this month</span></div></article>
      </section>
      <section className="storage-banner"><div className="mini-kitchen"><div className="mini-fridges">{refrigerators.slice(0,2).map(refrigerator=>{const model=fridgePresets.find(f=>f.id===refrigerator.modelId)||fridgePresets[0];return <div className="mini-fridge" key={refrigerator.id} style={{background:`linear-gradient(120deg,${model.color},#d7dddd)`}}>{foods.filter(f=>f.location.startsWith(`${refrigerator.id} · `)).slice(0,3).map(f=><span key={f.id}>{f.icon}</span>)}</div>})}{refrigerators.length>2&&<b className="mini-fridge-more">+{refrigerators.length-2}</b>}</div><div className="mini-cabinets">{cabinets.slice(0,cabinets.length>4?3:4).map(c=><i key={c.id} style={{background:c.color}}>{c.label.slice(0,1)}</i>)}{cabinets.length>4&&<i className="mini-cabinet-more">+{cabinets.length-3}</i>}</div></div><div><span>YOUR STORAGE MAP</span><h2>Know exactly where everything lives.</h2><p>{refrigerators.length} refrigerator{refrigerators.length===1?"":"s"} · {cabinets.length} labeled cabinet{cabinets.length===1?"":"s"}</p></div><button onClick={()=>setStorageOpen(true)}>Open visualizer →</button></section>
      <section className="content-grid">
        <article className="soon-card"><div className="section-head"><h2><span>◷</span> Use soon</h2><b>{soon.length} items</b></div><p>Plan your next meals around these first.</p><div className="soon-list">{soon.length?soon.slice(0,5).map(f=><div className="soon-row" key={f.id}><div className="food-icon">{f.image?<img src={f.image} alt=""/>:f.icon}</div><div className="food-copy"><strong>{f.name}</strong><small>{f.quantity} · {f.location}</small></div><div className={`days ${daysLeft(f.expiry)<=2?"urgent":""}`}><b>{daysLeft(f.expiry)}</b><small>{daysLeft(f.expiry)===1?"day":"days"} left</small></div><div className="soon-actions">{canDonate(f)&&<button className="donate-mini" onClick={()=>setDonateFood(f)} title={`Donate ${f.name}`}>♡</button>}<button onClick={()=>openEditFood(f)} title={`Edit ${f.name}`}>✎</button></div></div>):<div className="empty">🎉 Nothing expires this week.</div>}</div><div className="tip">💡 <span><b>Tonight’s tip:</b> Add spinach and avocado to eggs for a quick use-it-up meal.</span></div></article>
        <article className="inventory-card"><div className="section-head"><div><h2>Pantry inventory</h2><p>Sorted by expiry date</p></div><label className="search">⌕<input aria-label="Search pantry" placeholder="Search food" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
          <div className="chips">{["All",...categories.slice(0,4)].map(c=><button key={c} className={filter===c?"selected":""} onClick={()=>setFilter(c)}>{c}</button>)}</div>
          <div className="table-head"><span>Item</span><span>Quantity</span><span>Expires</span><span>Status</span><span></span></div>
          <div className="inventory-list">{sorted.map(f=>{const d=daysLeft(f.expiry);const done=!isActive(f);return <div className={`inventory-row ${done?"finished":""}`} key={f.id}><div className="item"><i>{f.image?<img src={f.image} alt=""/>:f.icon}</i><span><strong>{f.name}</strong><small>{f.category} · {f.location}</small></span></div><span>{f.quantity}</span><span>{fmt(f.expiry)}</span><select aria-label={`${f.name} status`} className={`food-status ${done?"done":d<=2?"red":d<=7?"amber":"green"}`} value={f.status||"Available"} onChange={e=>setFoodStatus(f.id,e.target.value as Food["status"])}><option>Available</option><option>Opened</option><option>Eaten</option><option>Consumed</option><option>Donated</option><option>Spoiled</option><option>Discarded</option></select><button onClick={()=>openEditFood(f)} title={`Edit ${f.name}`}>✎</button></div>})}</div>
        </article>
      </section>
      <section className="smart-suite"><div className="smart-title"><span>SMART PANTRY</span><h2>More ways to waste less</h2></div><div className="smart-grid"><button className="ai-launch" onClick={()=>setPanel("ai")}><i>✦</i><b>AI kitchen copilot</b><small>Ask, photograph, create rescue recipes, or use voice</small></button><button onClick={()=>setPanel("capture")}><i>⌁</i><b>Scan & import</b><small>Barcode, receipt photo, voice and batch entry</small></button><button onClick={()=>setPanel("alerts")}><i>◉</i><b>Expiry alerts</b><small>Browser, email-ready and calendar reminders</small></button><button onClick={()=>setPanel("household")}><i>♙</i><b>My household</b><small>{members.length} members · shared activity and assignments</small></button><button onClick={()=>setPanel("preferences")}><i>♡</i><b>Food preferences</b><small>Health goals, portions and preparation time</small></button><button onClick={()=>setPanel("insights")}><i>▥</i><b>Waste insights</b><small>₱{saved*145} estimated savings this month</small></button></div></section>
      <section className="public-pantry" id="public-pantry"><div className="public-pantry-head"><div><span>OPEN PUBLIC PANTRY</span><h2>Share food while it is still good.</h2><p>Offer safe food expiring within 3 days to nearby community members. Expired or spoiled food is automatically excluded.</p></div><div className="safety-badge">✓ Safety-first sharing</div></div><div className="public-pantry-grid"><article className="share-pantry"><div className="pantry-column-head"><div><h3>Share from your pantry</h3><p>Only eligible food shows a donation button.</p></div><b>{eligibleDonations.length} eligible</b></div><div className="eligible-list">{eligibleDonations.length?eligibleDonations.map(f=><div className="eligible-item" key={f.id}><div className="donation-thumb">{f.image?<img src={f.image} alt=""/>:f.icon}</div><div><b>{f.name}</b><small>{f.quantity} · expires {daysLeft(f.expiry)===0?"today":`in ${daysLeft(f.expiry)} day${daysLeft(f.expiry)===1?"":"s"}`}</small></div><button onClick={()=>setDonateFood(f)}>♡ Donate</button></div>):<div className="pantry-empty"><span>🌱</span><b>No food is eligible right now</b><p>Donation appears only for safe, active food expiring today or within 3 days.</p></div>}</div></article><article className="community-board"><div className="pantry-column-head"><div><h3>Available near you</h3><p>Public offers from the community.</p></div><b>{donations.filter(d=>daysLeft(d.expiryDate)>=0&&!d.claimed).length} available</b></div><div className="donation-board">{donationsLoading?<div className="pantry-empty"><span>◌</span><b>Opening the pantry…</b></div>:donations.filter(d=>daysLeft(d.expiryDate)>=0&&!d.claimed).length?donations.filter(d=>daysLeft(d.expiryDate)>=0&&!d.claimed).map(d=><div className="donation-card" key={d.id}><div className="donation-photo">{d.image?<img src={d.image} alt=""/>:<span>🥫</span>}<b>{daysLeft(d.expiryDate)===0?"Use today":`${daysLeft(d.expiryDate)}d left`}</b></div><div className="donation-copy"><span>FREE · {d.pickupArea}</span><h4>{d.foodName}</h4><p>{d.quantity}{d.note?` · ${d.note}`:""}</p><small>From {d.donorName}{d.pickupDetails?` · ${d.pickupDetails}`:""}</small>{d.contact&&<small>Contact: {d.contact}</small>}<button onClick={()=>claimDonation(d)}>Request & mark claimed →</button></div></div>):<div className="pantry-empty"><span>🤝</span><b>No public offers yet</b><p>Be the first to safely share food with the community.</p></div>}</div></article></div><div className="pantry-rule"><b>Food safety rule</b><span>Never donate food that smells unusual, has visible spoilage, has unsafe packaging, or has been stored incorrectly—even if its date has not passed.</span></div></section>
      <section className="recipes"><div className="recipe-title"><div><span>USE-IT-UP RECIPES</span><h2>Cook these next</h2><p>Ideas matched to the food that needs attention first.</p></div><button onClick={()=>showToast("Fresh recipe ideas generated from your pantry")}>↻ Refresh ideas</button></div><div className="recipe-grid">{recipes.map((r,i)=><article className="recipe-card" key={r.title}><div className={`recipe-art art-${i}`}>{r.emoji}<span>{r.meal}</span></div><div className="recipe-body"><div className="recipe-meta"><span>◷ {r.time}</span><b>Uses {r.matches.length} expiring {r.matches.length===1?"item":"items"}</b></div><h3>{r.title}</h3><p>{r.steps}</p><div className="ingredients">{r.matches.map(f=><span key={f.id}>{f.icon} {f.name} · {daysLeft(f.expiry)}d</span>)}</div><button onClick={()=>showToast(`${r.title} added to your meal plan`)}>Add to meal plan →</button></div></article>)}</div></section>
    </main>
    <nav className="mobile-nav"><button className="active">⌂<small>Home</small></button><button>▣<small>Pantry</small></button><button onClick={openAddFood} className="mobile-add">＋</button><button>◷<small>Use soon</small></button><button onClick={openPublicPantry}>♡<small>Donate</small></button></nav>
    {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closeFoodForm()}}><form key={editingFood?.id||"new"} className="modal enhanced-form" onSubmit={saveFood}><div className="modal-head"><div><span>SMART ENTRY</span><h2>{editingFood?"Edit food":"Add food"}</h2></div><button type="button" onClick={closeFoodForm}>×</button></div><p>Add a clear photo so everyone can recognize the item, then track its expiry and storage spot.</p><div className="photo-entry"><label className="food-photo-picker">{entryImage?<img src={entryImage} alt="Food preview"/>:<span><b>＋</b><small>Add food photo</small></span>}<input type="file" accept="image/*" capture="environment" onChange={e=>chooseFoodImage(e.target.files?.[0])}/></label><div><b>{entryImage?"Photo added":"Picture optional"}</b><small>Take a photo or choose one from your device. Images are resized before saving.</small>{entryImage&&<button type="button" onClick={()=>setEntryImage("")}>Remove photo</button>}</div></div><label>Food name<input name="name" required autoFocus placeholder="e.g. Whole wheat bread" defaultValue={editingFood?.name}/></label><div className="form-grid"><label>Quantity<input name="quantity" required placeholder="e.g. 1 loaf" defaultValue={editingFood?.quantity}/></label><label>Category<select name="category" defaultValue={editingFood?.category||categories[0]}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Exact storage location<select name="location" defaultValue={editingFood?.location||allLocations[0]}>{allLocations.map(x=><option key={x}>{x}</option>)}</select></label><label>Expiry / best-before<input name="expiry" type="date" required defaultValue={editingFood?.expiry}/></label><label>Purchase date<input name="purchased" type="date" defaultValue={editingFood?.purchased}/></label><label>Opened date<input name="opened" type="date" defaultValue={editingFood?.opened}/></label><label>Price (₱)<input name="price" type="number" min="0" step="0.01" placeholder="0.00" defaultValue={editingFood?.price||""}/></label><label>Amount remaining<select name="remaining" defaultValue={editingFood?.remaining??100}><option value="100">100% · Full</option><option value="75">75%</option><option value="50">50% · Half</option><option value="25">25% · Almost gone</option></select></label></div><div className="form-actions"><button type="button" onClick={closeFoodForm}>Cancel</button><button className="save-food">{editingFood?"Save changes →":"Add to pantry →"}</button></div></form></div>}
    {donateFood&&canDonate(donateFood)&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDonateFood(null)}}><form className="modal donation-form" onSubmit={offerDonation}><div className="modal-head"><div><span>PUBLIC PANTRY</span><h2>Donate {donateFood.name}</h2></div><button type="button" onClick={()=>setDonateFood(null)}>×</button></div><div className="donation-summary"><div className="donation-thumb">{donateFood.image?<img src={donateFood.image} alt=""/>:donateFood.icon}</div><div><b>{donateFood.quantity}</b><span>Expires {daysLeft(donateFood.expiry)===0?"today":`in ${daysLeft(donateFood.expiry)} day${daysLeft(donateFood.expiry)===1?"":"s"}`}</span></div></div><div className="form-grid"><label>Your name<input name="donorName" required placeholder="Community member"/></label><label>Pickup city / area<input name="pickupArea" required placeholder="City or neighborhood"/></label><label>Pickup details<input name="pickupDetails" placeholder="Public landmark or agreed meeting point"/></label><label>Contact method<input name="contact" placeholder="Optional contact method"/></label></div><label>Note for the recipient<textarea name="note" maxLength={220} placeholder="Packaging, storage instructions, or available pickup time"/></label><label className="safety-check"><input name="safeToShare" type="checkbox" required/><span><b>I confirm this food is safe to share.</b><small>It has no smell, visible spoilage, damaged packaging, or unsafe storage history.</small></span></label><div className="expiry-protection">🛡 Expired and spoiled food cannot be posted and will not appear in Public Pantry.</div><div className="form-actions"><button type="button" onClick={()=>setDonateFood(null)}>Cancel</button><button className="save-food">Post donation →</button></div></form></div>}
    {panel&&<div className="modal-backdrop smart-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setPanel(null)}}><section className="smart-panel"><div className="modal-head"><div><span>{panel==="ai"?"POWERED BY OPENAI":"SMART PANTRY"}</span><h2>{panel==="ai"?"Kitchen copilot":panel==="capture"?"Capture groceries":panel==="alerts"?"Never miss an expiry":panel==="household"?"My household":panel==="preferences"?"Food preferences":"Waste insights"}</h2></div><button onClick={()=>setPanel(null)}>×</button></div>
      {panel==="ai"&&<div className="ai-panel"><p>Ask about your pantry, generate recipes that rescue urgent food, analyze a label or food photo, or dictate a question.</p><div className="ai-quick"><button onClick={()=>void askAi("recipes","Create three practical rescue recipes.")}>🍳 Rescue recipes</button><button onClick={()=>{setAiQuestion("What should I use first today, and why?");void askAi("chat","What should I use first today, and why?")}}>◷ What to use first</button><label>▧ Analyze photo<input type="file" accept="image/*" capture="environment" onChange={e=>chooseAiImage(e.target.files?.[0])}/></label><button onClick={recordVoice}>{recording?"● Listening…":"◖ Voice question"}</button></div>{aiImage&&<div className="ai-image"><img src={aiImage} alt="Food selected for AI analysis"/><button onClick={()=>setAiImage("")}>Remove</button></div>}<div className="ai-compose"><textarea value={aiQuestion} onChange={e=>setAiQuestion(e.target.value)} maxLength={2000} placeholder="Ask: What can I cook tonight with the spinach and milk?"/><button disabled={aiLoading||!aiQuestion.trim()} onClick={()=>void askAi("chat")}>{aiLoading?"Thinking…":"Ask OpenAI →"}</button></div>{(aiLoading||aiAnswer)&&<div className="ai-answer"><div><b>Pantry Guardian</b>{aiAnswer&&<button onClick={listenToAnswer}>▶ Listen</button>}</div><p>{aiLoading?"Reviewing your pantry…":aiAnswer}</p></div>}<small className="ai-safety">AI can make mistakes. Verify dates, storage history, allergens, and signs of spoilage; when in doubt, discard the food.</small></div>}
      {panel==="capture"&&<div className="capture-panel"><p>Add a single item, scan a barcode, photograph a receipt or prepare a grocery batch.</p><div className="capture-grid"><article><i>▥</i><h3>Scan barcode</h3><div className="inline-entry"><input value={barcode} onChange={e=>setBarcode(e.target.value)} placeholder="Try 4800016641016"/><button onClick={scanBarcode}>Identify</button></div>{scanResult&&<b className="scan-result">✓ {scanResult}</b>}</article><label className="upload-card"><i>▧</i><h3>Receipt or expiry photo</h3><p>OpenAI Vision will identify visible food and dates for your review.</p><input type="file" accept="image/*" capture="environment" onChange={e=>chooseAiImage(e.target.files?.[0])}/><span>Analyze image</span></label><article><i>◖</i><h3>Voice entry</h3><p>Say items naturally, such as “two cartons of milk expiring Friday.”</p><button onClick={recordVoice}>{recording?"Listening…":"Start voice entry"}</button></article><article><i>＋</i><h3>Batch grocery trip</h3><p>Add multiple items using a quick repeating form.</p><button onClick={()=>{setPanel(null);openAddFood()}}>Start batch</button></article></div><div className="integration-note"><b>Delivery imports</b><span>Connect grocery email or delivery providers when credentials are available.</span><button onClick={()=>showToast("Integration request saved")}>Request integration</button></div></div>}
      {panel==="alerts"&&<div className="settings-panel"><p>Choose when and how Pantry Guardian should remind you.</p><label className="toggle-row"><span><b>Browser notifications</b><small>Alerts on this device</small></span><button className={alerts.browser?"on":""} onClick={requestAlerts}>{alerts.browser?"On":"Enable"}</button></label><label className="toggle-row"><span><b>Calendar reminders</b><small>Download reminders for your calendar</small></span><button className={alerts.calendar?"on":""} onClick={downloadCalendar}>Add reminder</button></label><label className="toggle-row"><span><b>Email reminders</b><small>Ready to connect to a delivery service</small></span><button onClick={()=>setAlerts(v=>({...v,email:!v.email}))} className={alerts.email?"on":""}>{alerts.email?"On":"Off"}</button></label>{alerts.email&&<label>Email address<input value={alerts.emailAddress} onChange={e=>setAlerts(v=>({...v,emailAddress:e.target.value}))} type="email" placeholder="name@example.com"/></label>}<label>First warning<select value={alerts.days} onChange={e=>setAlerts(v=>({...v,days:+e.target.value}))}><option value="1">1 day before</option><option value="3">3 days before</option><option value="5">5 days before</option><option value="7">7 days before</option></select></label><div className="alert-ladder"><span>7 days<br/><b>Plan</b></span><span>3 days<br/><b>Use soon</b></span><span>Today<br/><b>Rescue</b></span></div></div>}
      {panel==="household"&&<div className="household-panel"><p>Coordinate who bought, opened, or consumed food. Data is shared on this device until cloud accounts are connected.</p><div className="member-list">{members.map((m,i)=><article key={m}><i>{m.slice(0,1)}</i><span><b>{m}</b><small>{i===0?"Owner · recent actions":"Member · Pantry access"}</small></span>{i>0&&<button onClick={()=>setMembers(v=>v.filter(x=>x!==m))}>Remove</button>}</article>)}</div><div className="inline-entry"><input value={newMember} onChange={e=>setNewMember(e.target.value)} placeholder="Household member name"/><button onClick={()=>{if(newMember){setMembers(v=>[...v,newMember]);setNewMember("");showToast("Household member added")}}}>Invite</button></div><h3>Recent household activity</h3><div className="activity"><span>✓ An item was consumed</span><span>＋ A pantry item was added</span><span>↗ A storage location was updated</span></div></div>}
      {panel==="preferences"&&<div className="settings-panel"><p>Recipe suggestions will favor your cooking style, available time, and household size.</p><div className="goal-grid">{[["plantForward","Plant-forward"],["quickMeals","Quick meals"],["familyFriendly","Family-friendly"],["budgetFriendly","Budget-friendly"]].map(([k,label])=><button key={k} className={prefs[k as keyof typeof prefs]?"selected":""} onClick={()=>setPrefs(v=>({...v,[k]:!v[k as keyof typeof v]}))}>✓ {label}</button>)}</div><label>Maximum preparation time<input type="range" min="10" max="60" step="5" value={prefs.minutes} onChange={e=>setPrefs(v=>({...v,minutes:+e.target.value}))}/><b>{prefs.minutes} minutes</b></label><label>Servings<select value={prefs.servings} onChange={e=>setPrefs(v=>({...v,servings:+e.target.value}))}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><div className="preference-summary">Recipes are now optimized for {Object.entries(prefs).filter(([,v])=>v===true).length} cooking preferences, {prefs.minutes} minutes or less, serving {prefs.servings}.</div></div>}
      {panel==="insights"&&<div className="insights-panel"><div className="insight-stats"><article><small>Estimated savings</small><strong>₱{saved*145}</strong><span>↑ 18% this month</span></article><article><small>Food rescued</small><strong>{saved}</strong><span>{(saved*0.42).toFixed(1)} kg saved</span></article><article><small>Rescue rate</small><strong>{Math.min(100,68+saved*4)}%</strong><span>Household goal: 90%</span></article></div><h3>Waste risk by category</h3><div className="bars"><label>Produce <i style={{width:"78%"}}></i><b>High</b></label><label>Dairy <i style={{width:"52%"}}></i><b>Medium</b></label><label>Grains <i style={{width:"18%"}}></i><b>Low</b></label></div><div className="insight-callout"><b>Smart recommendation</b><p>You frequently rescue dairy at the last minute. Buy one carton less on your next grocery trip.</p><button onClick={()=>showToast("Added to shopping guidance")}>Use this advice</button></div><button className="download-report" onClick={()=>showToast("Monthly sustainability summary prepared")}>Download monthly report</button></div>}
    </section></div>}
    {storageOpen&&<div className="storage-overlay"><section className="storage-studio">
      <div className="studio-head"><div><span>STORAGE DESIGNER</span><h2>My kitchen map</h2><p>Select your real refrigerator model, then place every item in its matching zone.</p></div><button onClick={()=>setStorageOpen(false)}>×</button></div>
      <div className="studio-layout"><aside className="studio-controls">
        <div className="refrigerator-heading"><div><h3>Refrigerators</h3><small>{refrigerators.length} of 6 refrigerators</small></div><button type="button" onClick={addRefrigerator} disabled={refrigerators.length>=6}>＋ Add refrigerator</button></div>{refrigerators.length===0&&<div className="storage-empty-control"><b>No refrigerator added</b><small>Add one whenever you are ready to map refrigerated food.</small></div>}{refrigerators.map(refrigerator=>{const model=fridgePresets.find(f=>f.id===refrigerator.modelId)||fridgePresets[0];return <div className="refrigerator-control" key={refrigerator.id}><div className="storage-control-head"><b>{refrigerator.id}</b><button type="button" aria-label={`Delete ${refrigerator.id}`} onClick={()=>deleteRefrigerator(refrigerator)}>Delete</button></div><input aria-label={`${refrigerator.id} label`} value={refrigerator.label} onChange={e=>setRefrigerators(v=>v.map(item=>item.id===refrigerator.id?{...item,label:e.target.value}:item))}/><select aria-label={`${refrigerator.id} model`} value={refrigerator.modelId} onChange={e=>updateRefrigeratorModel(refrigerator.id,e.target.value)}>{fridgePresets.map(f=><option value={f.id} key={f.id}>{f.brand} {f.model} · {f.colorName}</option>)}</select><div className="selected-appliance"><i style={{background:model.color}}></i><div><b>{model.brand} {model.model}</b><small>{model.name}<br/>{model.type} · {model.capacity} · {model.colorName}</small></div></div></div>})}
        <div className="cabinet-heading"><div><h3>Cabinets</h3><small>{cabinets.length} of 12 cabinets</small></div><button type="button" onClick={addCabinet} disabled={cabinets.length>=12}>＋ Add cabinet</button></div>{cabinets.length===0&&<div className="storage-empty-control"><b>No cabinets added</b><small>Add a cabinet and customize its shelves and bins.</small></div>}{cabinets.map((c,i)=><div className="cabinet-control" key={c.id}><div className="storage-control-head"><b>{c.id}</b><button type="button" aria-label={`Delete ${c.id}`} onClick={()=>deleteCabinet(c)}>Delete</button></div><input aria-label={`${c.id} label`} value={c.label} onChange={e=>setCabinets(v=>v.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/><div className="cabinet-look-row"><input type="color" aria-label={`${c.id} color`} value={c.color} onChange={e=>setCabinets(v=>v.map((x,n)=>n===i?{...x,color:e.target.value}:x))}/><select aria-label={`${c.id} finish`} value={c.finish} onChange={e=>setCabinets(v=>v.map((x,n)=>n===i?{...x,finish:e.target.value}:x))}><option>Wood</option><option>Matte</option><option>Gloss</option><option>Painted</option></select></div><label className="shelf-count">Number of shelves<select aria-label={`${c.id} number of shelves`} value={c.shelfCount} onChange={e=>updateShelfCount(c,+e.target.value)}>{Array.from({length:8},(_,shelf)=><option key={shelf+1} value={shelf+1}>{shelf+1}</option>)}</select></label><div className="shelf-bin-settings">{Array.from({length:c.shelfCount},(_,shelf)=><label key={shelf}>Shelf {shelf+1} bins<select aria-label={`${c.id} shelf ${shelf+1} bins`} value={c.shelfBins[shelf]} onChange={e=>updateShelfBins(c,shelf,e.target.value as ShelfBins)}><option>None</option><option>Left bin</option><option>Right bin</option><option>Left &amp; right bins</option></select></label>)}</div></div>)}
      </aside><div className="storage-scene"><div className="fridge-wall">{refrigerators.map(refrigerator=>{const model=fridgePresets.find(f=>f.id===refrigerator.modelId)||fridgePresets[0];return <div className={`fridge model-${model.type.toLowerCase().replaceAll(" ","-")}`} style={{background:`linear-gradient(110deg,${model.color},#b9c0c0 52%,${model.color})`}} key={refrigerator.id}><div className="appliance-label">{refrigerator.label||refrigerator.id}<small>{model.brand} {model.model} · {model.colorName} · {foods.filter(f=>isActive(f)&&f.location.startsWith(`${refrigerator.id} · `)).length} items</small></div><div className="fridge-zones">{model.zones.map(zone=>{const location=`${refrigerator.id} · ${zone}`;return <div className="fridge-zone" key={zone}><label>{zone}</label><div>{foods.filter(f=>isActive(f)&&f.location===location).map(f=><button key={f.id} title={f.name}>{f.image?<img src={f.image} alt=""/>:f.icon}<small>{f.name}</small></button>)}</div></div>})}</div></div>})}{refrigerators.length===0&&<div className="storage-scene-empty">No refrigerator mapped</div>}</div><div className="cabinet-wall">{cabinets.map(c=><div className={`cabinet finish-${c.finish.toLowerCase()}`} style={{background:c.color}} key={c.id}><div className="cabinet-label">{c.label||c.id}</div>{Array.from({length:c.shelfCount},(_,shelfIndex)=>{const shelf=`${c.id} · Shelf ${shelfIndex+1}`;const bins=c.shelfBins[shelfIndex];return <div className="cabinet-shelf" key={shelf}><label>Shelf {shelfIndex+1}</label><div className="cabinet-shelf-items">{foods.filter(f=>isActive(f)&&(f.location===shelf||(shelfIndex===0&&f.location===c.id))).map(f=><span key={f.id} title={`${f.name} · Shelf ${shelfIndex+1}`}>{f.icon}<small>{f.name}</small></span>)}</div>{bins!=="None"&&<div className="cabinet-bins">{(bins==="Left bin"||bins==="Left & right bins")&&<div><label>Left bin</label>{foods.filter(f=>isActive(f)&&f.location===`${shelf} · Left bin`).map(f=><span key={f.id}>{f.icon}</span>)}</div>}{(bins==="Right bin"||bins==="Left & right bins")&&<div><label>Right bin</label>{foods.filter(f=>isActive(f)&&f.location===`${shelf} · Right bin`).map(f=><span key={f.id}>{f.icon}</span>)}</div>}</div>}</div>})}<small>{c.shelfCount} shelves · {c.finish} · {c.id}</small></div>)}{cabinets.length===0&&<div className="storage-scene-empty">No cabinets mapped</div>}</div></div>
      <aside className="placement-panel"><div><h3>Place & update food</h3><p>Choose the exact refrigerator compartment, cabinet shelf, or bin.</p></div>{foods.map(f=><label className={`placement-item ${!isActive(f)?"finished":""}`} key={f.id}><span>{f.icon}</span><b>{f.name}<small>{f.quantity}</small></b><select value={allLocations.includes(f.location)?f.location:"Unassigned"} onChange={e=>moveFood(f.id,e.target.value)}><optgroup label="Other"><option>Unassigned</option><option>Countertop</option></optgroup>{refrigerators.map(refrigerator=>{const model=fridgePresets.find(item=>item.id===refrigerator.modelId)||fridgePresets[0];return <optgroup label={`${refrigerator.id} · ${refrigerator.label} · ${model.brand} ${model.model}`} key={refrigerator.id}>{model.zones.map(zone=>{const location=`${refrigerator.id} · ${zone}`;return <option key={location}>{location}</option>})}</optgroup>})}{cabinets.map(c=><optgroup label={`${c.id} · ${c.label}`} key={c.id}><option>{c.id}</option>{cabinetLocationsFor(c).map(location=><option key={location}>{location}</option>)}</optgroup>)}</select><select value={f.status||"Available"} onChange={e=>setFoodStatus(f.id,e.target.value as Food["status"])}><option>Available</option><option>Opened</option><option>Eaten</option><option>Consumed</option><option>Donated</option><option>Spoiled</option><option>Discarded</option></select></label>)}</aside></div>
      <div className="studio-footer"><span>✓ {refrigerators.length} refrigerator{refrigerators.length===1?"":"s"}, {cabinets.length} cabinet{cabinets.length===1?"":"s"}, shelves, and bins save automatically</span><button onClick={()=>setStorageOpen(false)}>Done mapping</button></div>
    </section></div>}
    {toast&&<div className="toast">✓ {toast}</div>}
  </div>
}
